name: Generate gw_update.tar

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-package:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # Clone submodules with --recurse-submodules

      # 2. Generate the update archive using Docker
      - name: Generate retro-go_update.bin
        run: |
          docker run --rm --user $(id -u):$(id -g) -v ${{ github.workspace }}:/opt/workdir sylverb/retro-go-sd-builder \
            bash -l -c "make -j\$$(nproc) CHECK_DIRTY_SUBMODULE=0 COVERFLOW=1 SHARED_HIBERNATE_SAVESTATE=1 DISABLE_SPLASH_SCREEN=1 ENABLE_BOOT_OC=1 INTFLASH_BANK=2 CHEAT_CODES=1 release"

      # 3. Upload retro-go_update.bin artifact
      - name: Upload retro-go_update.bin artifact
        uses: actions/upload-artifact@v4
        with:
          name: retro-go_update.bin
          path: release/retro-go_update.bin

  release-package:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # Clone submodules with --recurse-submodules

      # 2. Generate the update files using Docker
      - name: Generate firmware_update.bin and gw_update.tar
        run: |
          docker run --rm --user $(id -u):$(id -g) -v ${{ github.workspace }}:/opt/workdir sylverb/retro-go-sd-builder \
            bash -l -c "make -j\$$(nproc) CHECK_DIRTY_SUBMODULE=0 COVERFLOW=1 SHARED_HIBERNATE_SAVESTATE=1 DISABLE_SPLASH_SCREEN=1 ENABLE_BOOT_OC=1 INTFLASH_BANK=2 CHEAT_CODES=1 release"

      # 3. Create a release and upload files
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      # 4. Add firmware update file as assets
      - name: Upload retro-go_update.bin to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/retro-go_update.bin
          asset_name: retro-go_update.bin
          asset_content_type: application/octet-stream
